apiVersion: apps/v1
kind: Deployment
metadata:
    name: matching-api
    labels:
        app: matching-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: matching-api
    template:
        metadata:
            labels:
                app: matching-api
        spec:
            containers:
                - name: matching-api
                  image: lavorocontainers.azurecr.io/matching-api:<tag>
                  ports:
                      - containerPort: 80
                  env:
                      - name: DB_CONNECTION_STRING
                        valueFrom:
                            secretKeyRef:
                                name: db-connection-string
                                key: DB_CONNECTION_STRING
