apiVersion: v1
kind: Service
metadata:
    name: matching-api
spec:
    selector:
        app: matching-api
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: ClusterIP
